[package]
name = "a-6"
version = "0.1.0"
edition = "2018"

[dependencies]
bitcoincore-rpc = "0.15"
dotenv = "0.15"
lazy_static = "1.4"
serde = { version = "1.0", features = ["derive"] }
serde_with = "1.10.0"
serde_json = "1.0"
petgraph = "0.6.0"